import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import OpenAI from "openai";

const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

/**
 * POST /api/ai/generate-market
 * Takes a natural-language prompt and returns structured market data
 * generated by GPT.
 *
 * Body: { prompt: string }
 * Response: { title, description, rules, resolutionSource, closeTime, expectedResolutionTime }
 */
export async function POST(req: NextRequest) {
  // Auth check
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const body = await req.json();
  const prompt = String(body.prompt ?? "").trim();

  if (!prompt) {
    return NextResponse.json({ error: "Prompt is required" }, { status: 400 });
  }

  try {
    const completion = await openai.chat.completions.create({
      model: "gpt-4o-mini",
      temperature: 0.7,
      messages: [
        {
          role: "system",
          content: `You are an assistant that creates prediction market questions for a college campus community platform. Given a user's idea, generate a well-structured prediction market.

Respond ONLY with valid JSON (no markdown, no code fences) in this exact format:
{
  "title": "A clear yes/no question (e.g. 'Will it snow in Evanston this week?')",
  "description": "1-2 sentences explaining what this market is about and what it resolves to",
  "rules": "Precise resolution criteria: what counts as YES and what counts as NO",
  "resolutionSource": "Where/how the outcome will be verified (e.g. 'Official weather data from weather.gov')",
  "closeTime": "ISO 8601 datetime string for when betting closes (pick a reasonable time based on the question, usually 1-7 days from now)",
  "expectedResolutionTime": "ISO 8601 datetime string for when the outcome is expected to be known (must be after closeTime)"
}

Today's date is ${new Date().toISOString().split("T")[0]}. Make the times reasonable for the question asked. Use times roughly 1-7 days from now unless the question implies a different timeframe.`,
        },
        {
          role: "user",
          content: prompt,
        },
      ],
    });

    const raw = completion.choices[0]?.message?.content ?? "";

    // Parse the JSON response
    let parsed;
    try {
      parsed = JSON.parse(raw);
    } catch {
      // Try to extract JSON from the response if it has extra text
      const jsonMatch = raw.match(/\{[\s\S]*\}/);
      if (jsonMatch) {
        parsed = JSON.parse(jsonMatch[0]);
      } else {
        return NextResponse.json(
          { error: "AI returned invalid format. Please try again." },
          { status: 500 }
        );
      }
    }

    return NextResponse.json({
      title: parsed.title ?? "",
      description: parsed.description ?? "",
      rules: parsed.rules ?? "",
      resolutionSource: parsed.resolutionSource ?? "",
      closeTime: parsed.closeTime ?? "",
      expectedResolutionTime: parsed.expectedResolutionTime ?? "",
    });
  } catch (err: any) {
    console.error("OpenAI error:", err);
    return NextResponse.json(
      { error: "AI generation failed: " + (err.message ?? "Unknown error") },
      { status: 500 }
    );
  }
}
